apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: covid-lab-state
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: mydaprtestredis:6379
    # value: redis-master.default.svc.cluster.local:6379
  - name: redisPassword
    value: ""
  - name: keyPrefix
    value: name
    # secretKeyRef:
    #   name: redis
    #   key: redis-password
  # - name: redisPassword
  #   value: "gUIknmorq9"
