apiVersion: apps/v1
kind: Deployment
metadata:
  name: pub-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      pub: console
  template:
    metadata:
      labels:
        pub: console
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "secretclient"
    spec:
      containers:
      - name: pub-site
        image: pub-demo:test3
        imagePullPolicy: Never